import { Command } from 'commander';
import { registerInitCommand } from './init';
import { registerSetCommand } from './set';
import { registerGetCommand } from './get';
import { registerListCommand } from './list';
import { registerDeleteCommand } from './delete';
import { registerExportCommand } from './export';
import { registerImportCommand } from './import';
import { registerRotateCommand } from './rotate';
import { registerRenameCommand } from './rename';
import { registerCopyCommand } from './copy';
import { registerMoveCommand } from './move';
import { registerInfoCommand } from './info';
import { registerSearchCommand } from './search';
import { registerDiffCommand } from './diff';
import { registerMergeCommand } from './merge';
import { registerTagCommand } from './tag';
import { registerHistoryCommand } from './history';
import { registerAuditCommand } from './audit';
import { registerPinCommand } from './pin';
import { registerBackupCommand } from './backup';
import { registerLockCommand } from './lock';
import { registerCompareCommand } from './compare';
import { registerCloneCommand } from './clone';
import { registerStatsCommand } from './stats';
import { registerTtlCommand } from './ttl';
import { registerEnvCommand } from './env';
import { registerFmtCommand } from './fmt';
import { registerWatchCommand } from './watch';
import { registerVerifyCommand } from './verify';
import { registerPruneCommand } from './prune';
import { registerLintCommand } from './lint';
import { registerTemplateCommand } from './template';
import { registerSchemaCommand } from './schema';
import { registerCompressCommand } from './compress';
import { registerDoctorCommand } from './doctor';
import { registerShareCommand } from './share';
import { registerWhoamiCommand } from './whoami';
import { registerPasswdCommand } from './passwd';
import { registerSnapshotCommand } from './snapshot';
import { registerTouchCommand } from './touch';
import { registerRandomizeCommand } from './randomize';
import { registerGrepCommand } from './grep';
import { registerGenerateCommand } from './generate';
import { registerCountCommand } from './count';
import { registerKeysCommand } from './keys';
import { registerResolveCommand } from './resolve';
import { registerReloadCommand } from './reload';
import { registerChecksumCommand } from './checksum';
import { registerExpireCommand } from './expire';
import { registerTruncateCommand } from './truncate';
import { registerTrimCommand } from './trim';
import { registerHeadCommand } from './head';
import { registerTailCommand } from './tail';
import { registerCatCommand } from './cat';
import { registerFlattenCommand } from './flatten';
import { registerPlaceholderCommand } from './placeholder';
import { registerSanitizeCommand } from './sanitize';
import { registerUppercaseCommand } from './uppercase';
import { registerSortCommand } from './sort';
import { registerMaskCommand } from './mask';
import { registerUniqueCommand } from './unique';
import { registerPrefixCommand } from './prefix';
import { registerSuffixCommand } from './suffix';
import { registerNamespaceCommand } from './namespace';
import { registerRedactCommand } from './redact';
import { registerEncodeCommand } from './encode';
import { registerExtractCommand } from './extract';
import { registerDefaultCommand } from './default';
import { registerReverseCommand } from './reverse';
import { registerSliceCommand } from './slice';
import { registerSwapCommand } from './swap';
import { registerPatchCommand } from './patch';
import { registerCastCommand } from './cast';
import { registerIntersectCommand } from './intersect';
import { registerSubtractCommand } from './subtract';
import { registerLowercaseCommand } from './lowercase';
import { registerFilterCommand } from './filter';
import { registerRenameKeyCommand } from './rename-key';
import { registerPluckCommand } from './pluck';
import { registerOmitCommand } from './omit';
import { registerInjectCommand } from './inject';
import { registerValidateCommand } from './validate';
import { registerTransformCommand } from './transform';
import { registerFreezeCommand } from './freeze';
import { registerGroupCommand } from './group';
import { registerRenameValueCommand } from './rename-value';
import { registerAliasCommand } from './alias';

export function registerAllCommands(program: Command): void {
  registerInitCommand(program);
  registerSetCommand(program);
  registerGetCommand(program);
  registerListCommand(program);
  registerDeleteCommand(program);
  registerExportCommand(program);
  registerImportCommand(program);
  registerRotateCommand(program);
  registerRenameCommand(program);
  registerCopyCommand(program);
  registerMoveCommand(program);
  registerInfoCommand(program);
  registerSearchCommand(program);
  registerDiffCommand(program);
  registerMergeCommand(program);
  registerTagCommand(program);
  registerHistoryCommand(program);
  registerAuditCommand(program);
  registerPinCommand(program);
  registerBackupCommand(program);
  registerLockCommand(program);
  registerCompareCommand(program);
  registerCloneCommand(program);
  registerStatsCommand(program);
  registerTtlCommand(program);
  registerEnvCommand(program);
  registerFmtCommand(program);
  registerWatchCommand(program);
  registerVerifyCommand(program);
  registerPruneCommand(program);
  registerLintCommand(program);
  registerTemplateCommand(program);
  registerSchemaCommand(program);
  registerCompressCommand(program);
  registerDoctorCommand(program);
  registerShareCommand(program);
  registerWhoamiCommand(program);
  registerPasswdCommand(program);
  registerSnapshotCommand(program);
  registerTouchCommand(program);
  registerRandomizeCommand(program);
  registerGrepCommand(program);
  registerGenerateCommand(program);
  registerCountCommand(program);
  registerKeysCommand(program);
  registerResolveCommand(program);
  registerReloadCommand(program);
  registerChecksumCommand(program);
  registerExpireCommand(program);
  registerTruncateCommand(program);
  registerTrimCommand(program);
  registerHeadCommand(program);
  registerTailCommand(program);
  registerCatCommand(program);
  registerFlattenCommand(program);
  registerPlaceholderCommand(program);
  registerSanitizeCommand(program);
  registerUppercaseCommand(program);
  registerSortCommand(program);
  registerMaskCommand(program);
  registerUniqueCommand(program);
  registerPrefixCommand(program);
  registerSuffixCommand(program);
  registerNamespaceCommand(program);
  registerRedactCommand(program);
  registerEncodeCommand(program);
  registerExtractCommand(program);
  registerDefaultCommand(program);
  registerReverseCommand(program);
  registerSliceCommand(program);
  registerSwapCommand(program);
  registerPatchCommand(program);
  registerCastCommand(program);
  registerIntersectCommand(program);
  registerSubtractCommand(program);
  registerLowercaseCommand(program);
  registerFilterCommand(program);
  registerRenameKeyCommand(program);
  registerPluckCommand(program);
  registerOmitCommand(program);
  registerInjectCommand(program);
  registerValidateCommand(program);
  registerTransformCommand(program);
  registerFreezeCommand(program);
  registerGroupCommand(program);
  registerRenameValueCommand(program);
  registerAliasCommand(program);
}
