import { Command } from 'commander';
import { registerInitCommand } from './init';
import { registerSetCommand } from './set';
import { registerGetCommand } from './get';
import { registerListCommand } from './list';
import { registerDeleteCommand } from './delete';
import { registerExportCommand } from './export';
import { registerImportCommand } from './import';
import { registerRotateCommand } from './rotate';
import { registerRenameCommand } from './rename';
import { registerCopyCommand } from './copy';
import { registerMoveCommand } from './move';
import { registerInfoCommand } from './info';
import { registerSearchCommand } from './search';
import { registerDiffCommand } from './diff';
import { registerMergeCommand } from './merge';
import { registerTagCommand } from './tag';
import { registerHistoryCommand } from './history';
import { registerAuditCommand } from './audit';
import { registerPinCommand } from './pin';
import { registerBackupCommand } from './backup';
import { registerLockCommand } from './lock';
import { registerCompareCommand } from './compare';
import { registerCloneCommand } from './clone';
import { registerStatsCommand } from './stats';
import { registerEnvCommand } from './env';
import { registerFmtCommand } from './fmt';
import { registerWatchCommand } from './watch';
import { registerVerifyCommand } from './verify';
import { registerPruneCommand } from './prune';
import { registerLintCommand } from './lint';
import { registerTemplateCommand } from './template';
import { registerSchemaCommand } from './schema';
import { registerCompressCommand } from './compress';
import { registerDoctorCommand } from './doctor';
import { registerShareCommand } from './share';
import { registerWhoamiCommand } from './whoami';
import { registerPasswdCommand } from './passwd';
import { registerSnapshotCommand } from './snapshot';
import { registerTouchCommand } from './touch';
import { registerRandomizeCommand } from './randomize';
import { registerTtlCommand } from './ttl';
import { registerGrepCommand } from './grep';

export function registerAllCommands(program: Command): void {
  registerInitCommand(program);
  registerSetCommand(program);
  registerGetCommand(program);
  registerListCommand(program);
  registerDeleteCommand(program);
  registerExportCommand(program);
  registerImportCommand(program);
  registerRotateCommand(program);
  registerRenameCommand(program);
  registerCopyCommand(program);
  registerMoveCommand(program);
  registerInfoCommand(program);
  registerSearchCommand(program);
  registerDiffCommand(program);
  registerMergeCommand(program);
  registerTagCommand(program);
  registerHistoryCommand(program);
  registerAuditCommand(program);
  registerPinCommand(program);
  registerBackupCommand(program);
  registerLockCommand(program);
  registerCompareCommand(program);
  registerCloneCommand(program);
  registerStatsCommand(program);
  registerEnvCommand(program);
  registerFmtCommand(program);
  registerWatchCommand(program);
  registerVerifyCommand(program);
  registerPruneCommand(program);
  registerLintCommand(program);
  registerTemplateCommand(program);
  registerSchemaCommand(program);
  registerCompressCommand(program);
  registerDoctorCommand(program);
  registerShareCommand(program);
  registerWhoamiCommand(program);
  registerPasswdCommand(program);
  registerSnapshotCommand(program);
  registerTouchCommand(program);
  registerRandomizeCommand(program);
  registerTtlCommand(program);
  registerGrepCommand(program);
}
